# Generated by Django 3.2.9 on 2021-12-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='Address2',
            new_name='address2',
        ),
    ]
