# Generated by Django 3.2.9 on 2021-12-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20211217_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='zip_code',
            field=models.IntegerField(default=''),
        ),
    ]
