# Generated by Django 3.2.9 on 2021-12-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_checkout_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
