# Generated by Django 3.2.9 on 2021-12-17 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_checkout_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
