# Generated by Django 3.2.9 on 2021-12-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_checkout_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='address',
            new_name='desc',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='city',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='id',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='state',
        ),
        migrations.AddField(
            model_name='checkout',
            name='product_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
